### ISSUE TITLE
Issue related to grapesjs

### ISSUE THREAD

**Issue by Abhisheknanda1344463** [sura2k/files#1]
hi @sura2k  
First of all Sorry.
This is not the right way to ask you for help but TBH I didn't find any other thing where should i ask.

Here is the link in which you've commented for adding traits for wrapper in grapesjs
https://github.com/artf/grapesjs/issues/1146
Could you please explain how can i perform init function for trait of wrapper

Here is my link-: 
https://github.com/artf/grapesjs/issues/3237

Any help would be appreciated Thanks.

**Comment by sura2k** [comment]
@Abhisheknanda1344463 hey, sorry I didn't see your message, but anyway I don't remember anything now. If I have committed those changes here, you would find it or check the artf/grapesjs#1146 tip that artf has given and try to find out the way. But now grapesjs should be improved lot more there can be developer guides too in the original repo.
